Back Propagation - Regression - Using Keras

In [40]:
import numpy as np
import pandas as pd
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa','profile_score','lpa'])
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [41]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

model=Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [42]:
model.get_weights()
new_weights=[np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
             np.array([0.,0.],dtype=np.float32),
             np.array([[0.1],[0.1]],dtype=np.float32),
             np.array([0.],dtype=np.float32)]
model.set_weights(new_weights)
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [43]:
from flax.nnx import optimizer
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss="mean_squared_error",optimizer=optimizer)

In [44]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=100,verbose=1,batch_size=1)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 27.9041  
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 27.5813 
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 27.2574 
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 26.9185 
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 26.5873 
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 26.1998
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25.8610 
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 25.4731 
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25.0780 
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 24.6668 
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24.2559
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 23.8235 
Epoch 13/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 23.3924 
Epoch 14/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 22.9792 
Epoch 15/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 22.5182
Epo

In [45]:
model.get_weights()

[array([[0.38406628, 0.38406628],
        [0.3905895 , 0.3905895 ]], dtype=float32),
 array([0.29158399, 0.29158399], dtype=float32),
 array([[0.39307812],
        [0.39307812]], dtype=float32),
 array([0.2154806], dtype=float32)]

Back Propagation - Regression - Without using Keras

In [2]:
import numpy as np
import pandas as pd
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa','profile_score','lpa'])
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [3]:
def initialize_parameters(layer_dims):
  np.random.seed(3)
  parameters={}
  L=len(layer_dims)
  for i in range(1,L):
    parameters['w'+str(i)]=np.ones((layer_dims[i-1],layer_dims[i]))*0.1
    parameters['b'+str(i)]=np.zeros((layer_dims[i],1))
  return parameters

In [4]:
initialize_parameters([2,2,1])

{'w1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'w2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [8]:
def linear_forward(A_prev,w,b):
  Z=np.dot(w.T,A_prev) + b
  return Z

In [25]:
def L_layer_forward(X, parameters):
  A=X
  L=len(parameters)//2  #number of layers in the neural network
  for i in range(1,L+1):
    A_prev=A
    w1=parameters['w'+str(i)]
    b1=parameters['b'+str(i)]
    #print("A"+str(i-1)+":",A_prev)
    #print("w"+str(i)+":",w1)
    #print("b"+str(i)+":",b1)
    #print("--"*20)
    A=linear_forward(A_prev,w1,b1)
    #print("A"+str(i)+": ",A)
    #print("**"*20)
  return A,A_prev

In [17]:
X=df[['cgpa','profile_score']].values[0].reshape(2,1) #Shape(no of features, no. of training example)
y=df[['lpa']].values[0][0]
parameters=initialize_parameters([2,2,1])
y_hat,A1=L_layer_forward(X, parameters)
y_hat=y_hat[0][0]

A0: [[8]
 [8]]
w1: [[0.1 0.1]
 [0.1 0.1]]
b1: [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1: [[1.6]
 [1.6]]
w2: [[0.1]
 [0.1]]
b2: [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************


In [22]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['w2'][0][0]=parameters['w2'][0][0]+(0.001*2*(y-y_hat)*A1[0][0])
  parameters['w2'][1][0]=parameters['w2'][1][0]+(0.001*2*(y-y_hat)*A1[1][0])
  parameters['b2'][0][0]=parameters['b2'][0][0]+(0.001*2*(y-y_hat))
  parameters['w1'][0][0]=parameters['w1'][0][0]+(0.001*2*(y-y_hat)*parameters['w2'][0][0]*X[0][0])
  parameters['w1'][0][1]=parameters['w1'][0][1]+(0.001*2*(y-y_hat)*parameters['w2'][0][0]*X[1][0])
  parameters['b1'][0][0]=parameters['b1'][0][0]+(0.001*2*(y-y_hat)*parameters['w2'][0][0])
  parameters['w1'][1][0]=parameters['w1'][1][0]+(0.001*2*(y-y_hat)*parameters['w2'][1][0]*X[0][0])
  parameters['w1'][1][1]=parameters['w1'][1][1]+(0.001*2*(y-y_hat)*parameters['w2'][1][0]*X[1][0])
  parameters['b1'][1][0]=parameters['b1'][1][0]+(0.001*2*(y-y_hat)*parameters['w2'][1][0])

In [18]:
parameters

{'w1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'w2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [23]:
update_parameters(parameters,y,y_hat,A1,X)
parameters

{'w1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'w2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.00736]])}

In [38]:
from numpy.random.mtrand import f
parameters=initialize_parameters([2,2,1])
epochs=6
for i in range(epochs):
  Loss=[]
  for j in range(df.shape[0]):
    X=df[['cgpa','profile_score']].values[j].reshape(2,1) #Shape(no of features, no. of training example)
    y=df[['lpa']].values[j][0]
    y_hat,A1=L_layer_forward(X,parameters)
    y_hat=y_hat[0][0]
    update_parameters(parameters,y,y_hat,A1,X)
    Loss.append((y-y_hat)**2)
  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  26.28249792398698
Epoch -  2 Loss -  19.438253848220803
Epoch -  3 Loss -  10.139874435827522
Epoch -  4 Loss -  3.385561305106485
Epoch -  5 Loss -  1.3198454128484565
Epoch -  6 Loss -  1.152495614758268


{'w1': array([[0.27471938, 0.4117227 ],
        [0.28929479, 0.44063965]]),
 'b1': array([[0.02962621],
        [0.0322573 ]]),
 'w2': array([[0.433827  ],
        [0.51452649]]),
 'b2': array([[0.12010894]])}