Back Propagation - Using Keras

In [28]:
import numpy as np
import pandas as pd
df=pd.DataFrame([[8,8,1],[6,7,0],[8,10,1],[9,12,1]], columns=['cgpa','profile_score','lpa'])
df

,cgpa,profile_score,lpa
0,8,8,1
1,6,7,0
2,8,10,1
3,9,12,1


In [29]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

model=Sequential()
model.add(Dense(2,activation='sigmoid',input_dim=2))
model.add(Dense(1,activation='sigmoid'))
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [35]:
new_weights=[np.array([[0.1, 0.1 ],
[ 0.1,  0.1]], dtype=np.float32),
np.array([0., 0.], dtype=np.float32),
np.array([[0.1  ],
[0.1]], dtype=np.float32),
np.array([0.], dtype=np.float32)]
model.set_weights(new_weights)
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [36]:
from keras.optimizers import Adam
optimizer=Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy',optimizer=optimizer)

In [37]:
model.fit(df.iloc[:,0:-1].values,df.iloc[:,-1].values,epochs=100,verbose=1,batch_size=1)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.6520 
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6493  
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6483 
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6472 
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6463 
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6446 
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6436 
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6427 
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6414 
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6408 
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6396 
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6388 
Epoch 13/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6369 
Epoch 14/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6366 
Epoch 15/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6350 
Epoch 16/100
4/4 

Back Propagation - Without using Keras

In [1]:
import numpy as np
import pandas as pd
df=pd.DataFrame([[8,8,1],[6,7,0],[8,10,1],[9,12,1]], columns=['cgpa','profile_score','lpa'])
df

,cgpa,profile_score,lpa
0,8,8,1
1,6,7,0
2,8,10,1
3,9,12,1


In [2]:
def initialize_parameters(layer_dims):
  #np.random.seed(3)
  parameters={}
  L=len(layer_dims)
  for i in range(1,L):
    parameters['w'+str(i)]=np.ones((layer_dims[i-1],layer_dims[i]))*0.1
    parameters['b'+str(i)]=np.zeros((layer_dims[i],1))
  return parameters

In [5]:
def sigmoid(z):
  return 1/(1+np.exp(-z))

In [6]:
def linear_forward(A_prev,w,b):
  A=np.dot(w.T,A_prev)+b
  return sigmoid(A)

In [7]:
def L_layer_forward(X, parameters):
  A=X
  L=len(parameters)//2
  for i in range(1,L+1):
    A_prev=A
    w1=parameters['w'+str(i)]
    b1=parameters['b'+str(i)]
    A=linear_forward(A_prev,w1,b1)
  return A,A_prev

In [9]:
X=df[['cgpa','profile_score']].values[0].reshape(2,1)
y=df[['lpa']].values[0][0]
parameters=initialize_parameters([2,2,1])
y_hat,A1=L_layer_forward(X, parameters)
y_hat=y_hat[0][0]
X,y,parameters,y_hat,A1

(array([[8],
        [8]]),
 np.int64(1),
 {'w1': array([[0.1, 0.1],
         [0.1, 0.1]]),
  'b1': array([[0.],
         [0.]]),
  'w2': array([[0.1],
         [0.1]]),
  'b2': array([[0.]])},
 np.float64(0.5415051895671072),
 array([[0.83201839],
        [0.83201839]]))

In [15]:
def update_parameters(parameters,y,y_hat,A1,X,learn_rate):
  parameters['w2'][0][0]=parameters['w2'][0][0]+(learn_rate * (y-y_hat)*A1[0][0])
  parameters['w2'][1][0]=parameters['w2'][1][0]+(learn_rate * (y-y_hat)*A1[1][0])
  parameters['b2'][0][0]=parameters['b2'][0][0]+(learn_rate * (y-y_hat))
  parameters['w1'][0][0]=parameters['w1'][0][0]+(learn_rate * (y-y_hat)*parameters['w2'][0][0]*X[0][0])
  parameters['w1'][0][1]=parameters['w1'][0][1]+(learn_rate * (y-y_hat)*parameters['w2'][0][0]*X[1][0])
  parameters['b1'][0][0]=parameters['b1'][0][0]+(learn_rate * (y-y_hat)*parameters['w2'][0][0])
  parameters['w1'][1][0]=parameters['w1'][1][0]+(learn_rate * (y-y_hat)*parameters['w2'][1][0]*X[0][0])
  parameters['w1'][1][1]=parameters['w1'][1][1]+(learn_rate * (y-y_hat)*parameters['w2'][1][0]*X[1][0])
  parameters['b1'][1][0]=parameters['b1'][1][0]+(learn_rate * (y-y_hat)*parameters['w2'][1][0])
  return parameters

In [27]:
# epoch implementation
parameters=initialize_parameters([2,2,1]); epochs=25001; lr=0.0001
for i in range(epochs):
  Loss=[]
  for j in range(df.shape[0]):
    X=df[['cgpa','profile_score']].values[j].reshape(2,1)
    y=df[['lpa']].values[j][0]
    y_hat,A1=L_layer_forward(X, parameters)
    y_hat=y_hat[0][0]
    update_parameters(parameters,y,y_hat,A1,X,lr)
    Loss.append((-y*np.log(y_hat))-((1-y)*np.log(1-y_hat)))
  if i%1000==0:
    print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  0.6518166979104234
Epoch -  1001 Loss -  0.6106385667875524
Epoch -  2001 Loss -  0.590285665241658
Epoch -  3001 Loss -  0.5791375994454547
Epoch -  4001 Loss -  0.5725627108139588
Epoch -  5001 Loss -  0.5686158944976638
Epoch -  6001 Loss -  0.5662241708548846
Epoch -  7001 Loss -  0.5647621370999091
Epoch -  8001 Loss -  0.5638613791727449
Epoch -  9001 Loss -  0.563302719704267
Epoch -  10001 Loss -  0.5629543357433942
Epoch -  11001 Loss -  0.5627361203174248
Epoch -  12001 Loss -  0.5625989538941591
Epoch -  13001 Loss -  0.5625124902661656
Epoch -  14001 Loss -  0.5624578654812088
Epoch -  15001 Loss -  0.5624232944389036
Epoch -  16001 Loss -  0.5624013847473689
Epoch -  17001 Loss -  0.5623874843775661
Epoch -  18001 Loss -  0.5623786582170517
Epoch -  19001 Loss -  0.562373050579893
Epoch -  20001 Loss -  0.5623694863045223
Epoch -  21001 Loss -  0.5623672202215119
Epoch -  22001 Loss -  0.5623657793367494
Epoch -  23001 Loss -  0.5623648631805327
Epoch - 

{'w1': array([[2.21412527, 2.76492303],
        [2.21392064, 2.76464778]]),
 'b1': array([[0.07441563],
        [0.0744324 ]]),
 'w2': array([[0.39855021],
        [0.39843556]]),
 'b2': array([[0.29901421]])}